### ISSUE TITLE
[GLPI 9.3.3] Fatal error - Class 'AllAssets' not found on /front/allassets.php

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/tag#70]
`Fatal error: Uncaught Error: Class 'AllAssets' not found in /data/applis/glpi/9.3.3/plugins/tag/hook.php:71 Stack trace: #0 /data/applis/glpi/9.3.3/inc/plugin.class.php(1462): plugin_tag_getAddSearchOptionsNew('AllAssets') #1 /data/applis/glpi/9.3.3/inc/search.class.php(5833): Plugin::getAddSearchOptionsNew('AllAssets') #2 /data/applis/glpi/9.3.3/inc/search.class.php(5568): Search::getOptions('AllAssets', true) #3 /data/applis/glpi/9.3.3/ajax/searchrow.php(58): Search::getCleanedOptions('AllAssets') #4 /data/applis/glpi/9.3.3/inc/search.class.php(2182): include('/data/applis/gl...') #5 /data/applis/glpi/9.3.3/inc/search.class.php(76): Search::showGenericSearch('AllAssets', Array) #6 /data/applis/glpi/9.3.3/front/allassets.php(45): Search::show('AllAssets') #7 {main} thrown in /data/applis/glpi/9.3.3/plugins/tag/hook.php on line 71`

**Comment by tsmr** [comment]
Solution add this ? 

```
if (itemtype == 'AllAssets') {
	return [];
}
```
